spring.application.name=LibraryManagementBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/librarydb
spring.datasource.username=libraryuser
spring.datasource.password=librarypass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
